version: "3"

services:
  geekshop_db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
  geekshop:
    image: python:latest
    depends_on:
      - geekshop_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/${DOMAIN_NAME}/html/
    entrypoint: /var/www/${DOMAIN_NAME}/html/entrypoint_geekshop.sh
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/${DOMAIN_NAME}/html/
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - geekshop
    restart: always
