# Generated by Django 3.2.3 on 2021-07-26 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 22, 44, 53, 568421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '-'), ('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
    ]
